name: 定期実行+GitPushごとに実行

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: 'npm'

    # キャッシュ
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }} 
        restore-keys: npm-

    # インストール
    - name: npm install command
      run: npm install
    
    # 実際のコマンド
    - name: main action...
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: >
        npm run main

